appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: LSeIYCeezW0Y1cNqsA2cuc2CeYaYVUFeK+HlitJs3+KFMYICaW8l439sApXTI4ALsOQmC85KrmDiCFb+fNIYrjg2od9BirQt6BprXXY7cvHip7trPI/lvCYMS3rP3vaVQLa2zDTXpc7HD31fUnIOQ/Qh4PadnKGiiXQ9MEFHxIXhUUIaHV0Klw+c788MRRYWX9ITy69DszTQUUGXr8pG/BKjK51DgcxoGqwlraolZ4+K1TgSOA7opoZHwQ6j8j1WL9I8tanN1JyMbTB3RkgzNAziZ27vX/boh2TC2Jta3wJ7QEEgQEeqAmXhr6qjTBoYcQyoG2FG3QJ6wktWrnF4asCH0IB0PtAMcSQQzYsfy2ann+C79DGt4Mb1WLqCumuzfyUWhXmb4NWXF9CzhcznRY87B+uwAMuPjoIiwa+txJMIL2HpMm59OguHnDVT+CZOGrqtlRgVomuT/BbVl5c38FgkK8HgXxn09CGvYJYb/wZIU2Muq27R8Y5t50qvH+FgG7e3Go/0uh/67yHCfmkuwsSCJLpDJqOdASBj6qUhGDCA+i8jSXRhy/8ZjXQx+ySOCDjn6UUWMZCBcEzIXp+nm5GBKqqehaf8L2PiHYhWgQB6fmPjc21+nixt+iVoGZokoUkgNcr/hk7/y7ZD/S/IyR5kFCZ9VlYrbHodzjkClFo=
